### ISSUE TITLE
Not finding Arky

### ISSUE THREAD

**Issue by SpaceGuildIntern** [Nijmegen-Consultancy-Group/arkprofitcalculator#1]
Collecting Arky==0.3 (from -r requirements.txt (line 6))
  Could not find a version that satisfies the requirement Arky==0.3 (from -r requirements.txt (line 6)) (from versions: 0.4.1)
No matching distribution found for Arky==0.3 (from -r requirements.txt (line 6))

**Comment by KaiserKarel** [comment]
see: https://github.com/Nijmegen-Consultancy-Group/arkprofitcalculator/issues/3

apparently toons removes previous versions of arky from pypi, which causes pip to not be able to find them
